### PR TITLE
Fix error causing IR:H to fail

### PR DESCRIPTION
**Pull request by 0secure**
Number was not properly created as a Decimal (D) object.

### CODE REVIEW

**Comment by orf** [comment]
Oh boy, not sure how I missed this

**Comment by orf** [comment]
Could you add the failing vector to one of the test files if you do not mind?

**Comment by dgaus** [comment]
Oh @orf still watching this :) Have you still got merge access? I just merged it before I saw your comment

**Comment by orf** [comment]
I forgot all about this repo to be honest, so apparently yes! Nope, but it's fine though 👌

**Comment by dgaus** [comment]
I guess you still have the pypi project ownership, I can update the release number if you want to so you can push a new release?

**Comment by orf** [comment]
What is your PyPi username? I can add you as a collaborator?

**Comment by dgaus** [comment]
Yeah, sure, same as here, dgaus

**Comment by orf** [comment]
Ok, added you as an owner to this and wordinserter 👍

**Comment by dgaus** [comment]
Thanks, want me to try pushing the new release?

**Comment by orf** [comment]
Sure, if that's cool? I've bumped the version. If it fails or whatever I can publish one

**Comment by dgaus** [comment]
Done :+1:

**Pull request merged**
