### PR TITLE
Add CVSS v3.1 support

### LINKED ISSUE #7: add cvss 3.1 support
https://www.first.org/cvss/user-guide#CVSS-Version-3-1-Release

### PR DESCRIPTION
**Pull request by luc-x41**
This commit adds support for CVSS v3.1 with tests.

The test data was taken, like the existing ones, from https://github.com/skontar/cvss (as well as locally running millions of random tests generated using the JavaScript code on `first.org`).

The difference between 3.0 and 3.1 is one line of code, so this basically added an if-statement in `cvss3/calculations.py` to avoid duplication and a way for the code to know which line it should use, plus a lot of code to handle and test everything around the different versions.

Fixes #7

### CODE REVIEW

**Comment by dgaus** [comment]
Hi, thanks for the PR. In general it looks good but the use of the integer `31` as a version constant feels odd. Could you make this into a either Decimal or a "3.1" string? @orf I don't know if you are too busy to review this, do you want to take a look?

**Comment by orf** [comment]
I agree - can we use `3.1` rather than `31`? I've had a quick look and I don't think we assume the version is an integer anywhere.

Overall this looks excellent, however I don't have permission to merge this anymore, let alone publish it :(

Edit: I can publish it, but I can't merge to this repository anymore. Perhaps we should fork it to somewhere we both control?

**Comment by dgaus** [comment]
I don't have write permissions either, I think forking it is a good idea as I doubt anyone at Context will be working on this

**Comment by orf** [comment]
Ok, I can fork this to my account and merge later today/tomorrow, but if you want to fork it to your account and do the same then be my guest 👍

**Comment by dgaus** [comment]
Go ahead, it's your baby after all :grinning:

**Comment by luc-x41** [comment]
Hey guys, thanks for the replies :)

You mean the `VERSION` constant right? I guess I was using "31" in so many places that I forgot the decimal could be used here.

The class name or directory name can't be 3.1 by the way: while python supports importing from subfolders with a `.` and we could abuse that, the subdirectory may not start with a number.

Let me know in which repo to do the new pull request :)

**Comment by dgaus** [comment]
Yes, I don't mind the modules / classes being named cvss31, but `VERSION = 31` feels weird

**Comment by luc-x41** [comment]
Pushed the version change :)

@orf Could you create the fork?

**Comment by orf** [comment]
Done! https://github.com/orf/cvsslib

If you could make the PR there that would make things simpler, otherwise I will merge it manually tonight and do a release 👍

**Comment by orf** [comment]
This is now merged to https://github.com/orf/cvsslib. I'll do a release soon, can you close this MR please? 👍

**Pull request closed without merging**
